2022-10-31 00:29:47,783 INFO    MainThread:9019 [internal.py:wandb_internal():92] W&B internal server running at pid: 9019, started at: 2022-10-31 00:29:47.783457
2022-10-31 00:29:47,784 DEBUG   HandlerThread:9019 [handler.py:handle_request():131] handle_request: run_start
2022-10-31 00:29:47,785 INFO    WriterThread:9019 [datastore.py:open_for_write():77] open: /home/ruihan/or/Differentiable-ROUGE-score/wandb/offline-run-20221031_002946-2wyzh18j/run-2wyzh18j.wandb
2022-10-31 00:29:47,786 DEBUG   HandlerThread:9019 [meta.py:__init__():36] meta init
2022-10-31 00:29:47,786 DEBUG   HandlerThread:9019 [meta.py:__init__():50] meta init done
2022-10-31 00:29:47,786 DEBUG   HandlerThread:9019 [meta.py:probe():210] probe
2022-10-31 00:29:47,792 DEBUG   HandlerThread:9019 [meta.py:_setup_git():200] setup git
2022-10-31 00:29:47,801 DEBUG   HandlerThread:9019 [meta.py:_setup_git():207] setup git done
2022-10-31 00:29:47,801 DEBUG   HandlerThread:9019 [meta.py:_save_pip():54] save pip
2022-10-31 00:29:47,802 DEBUG   HandlerThread:9019 [meta.py:_save_pip():68] save pip done
2022-10-31 00:29:47,802 DEBUG   HandlerThread:9019 [meta.py:_save_conda():75] save conda
2022-10-31 00:29:57,104 DEBUG   HandlerThread:9019 [meta.py:_save_conda():85] save conda done
2022-10-31 00:29:57,104 DEBUG   HandlerThread:9019 [meta.py:probe():248] probe done
2022-10-31 00:30:40,453 WARNING MainThread:9019 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-10-31 00:30:44,263 WARNING MainThread:9019 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-10-31 00:30:44,264 ERROR   MainThread:9019 [internal.py:wandb_internal():155] Internal process interrupted.
2022-10-31 00:30:44,801 INFO    SenderThread:9019 [sender.py:finish():1075] shutting down sender
2022-10-31 00:30:45,035 INFO    WriterThread:9019 [datastore.py:close():281] close: /home/ruihan/or/Differentiable-ROUGE-score/wandb/offline-run-20221031_002946-2wyzh18j/run-2wyzh18j.wandb
2022-10-31 00:30:45,054 INFO    HandlerThread:9019 [handler.py:finish():739] shutting down handler
2022-10-31 00:30:45,054 INFO    MainThread:9019 [internal.py:handle_exit():79] Internal process exited
